"""
Modal.com serverless deployment for Stable Fast 3D (SF3D).
Converts images generated by SD-XL into 3D .glb models.

Architecture:
  - Deploys on Modal's Nvidia A10G 24GB
  - Image-to-3D reconstruction via Stable Fast 3D
  - Input: PNG image bytes (from SD-XL output)
  - Output: .glb model bytes
"""

import io
import os
import modal
from modal import App, Image as ModalImage

# --- Modal App Definition ---
app = modal.App("greenscape-sf3d")

# --- Build a Modal Image ---
sf3d_image = (
    ModalImage.from_registry(
        "nvidia/cuda:12.4.0-devel-ubuntu22.04",
        setup_dockerfile_commands=[
            "RUN apt-get update && apt-get install -y python3 python3-pip git ninja-build python-is-python3",
        ]
    )
    .pip_install(
        "torch==2.6.0",
        "torchvision==0.21.0",
        "numpy<2",
        "Pillow==11.1.0",
        "trimesh==4.5.2",
        "scipy==1.15.0",
        "huggingface_hub==0.29.0",
    )
    .env({
        "HF_HUB_ENABLE_HF_TRANSFER": "0",
        "USE_CUDA": "1",
        "TORCH_CUDA_ARCH_LIST": "8.6",
    })
    .run_commands([
        # Clone repo ke /root/sf3d (root directory tidak punya setup.py)
        'git clone https://github.com/Stability-AI/stable-fast-3d.git /root/sf3d',
        # Hapus __init__.py root yang merupakan ComfyUI custom node (import comfy)
        # agar tidak mengganggu import sf3d.system.SF3D
        'rm -f /root/sf3d/__init__.py',
        # requirements.txt berisi relative paths (./texture_baker/, ./uv_unwrapper/).
        # Harus cd dulu ke /root/sf3d agar relative path di-resolve dengan benar.
        'cd /root/sf3d && pip install -r requirements.txt',
        # Install sub-packages texture_baker dan uv_unwrapper (punya setup.py sendiri)
        'cd /root/sf3d/texture_baker && pip install .',
        'cd /root/sf3d/uv_unwrapper && pip install .',
        # Upgrade ninja
        'pip install ninja --upgrade',
    ])
)

# Images larger than this will be resized to speed up 3D reconstruction
MAX_IMAGE_SIZE = 1024

import os

# Load HF token directly from .env without importing core (which fails in modal cloud context)
env_path = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), ".env")

@app.cls(
    image=sf3d_image,
    gpu="A10G",
    timeout=600,       # 3D reconstruction can take longer
    secrets=[modal.Secret.from_dotenv(env_path)]
)
class SF3DGenerator:
    # Model akan diinisialisasi di load_model(), bukan di __init__
    model: object = None
    device: object = None

    @modal.enter()
    def load_model(self):
        """Load the Stable Fast 3D model into GPU memory."""
        import sys
        import os
        import torch  # type: ignore
        import rembg  # type: ignore
        
        print("🚀 Loading Stable Fast 3D model onto GPU...")
        self.device = torch.device("cuda")
        self.rembg_session = rembg.new_session("u2net")
        
        # Hapus __init__.py root (ComfyUI node) sudah dilakukan saat build image.
        # Sekarang kita bisa import sf3d.system secara normal tanpa trigger comfy.
        sys.path.insert(0, "/root/sf3d")
        from sf3d.system import SF3D  # type: ignore
        
        # HF_TOKEN is expected by huggingface_hub
        if "HF_API_TOKEN" in os.environ:
            os.environ["HF_TOKEN"] = os.environ["HF_API_TOKEN"]
            
        self.model = SF3D.from_pretrained(
            "stabilityai/stable-fast-3d",
            config_name="config.yaml",
            weight_name="model.safetensors",
        )
        self.model.eval()
        self.model.to(self.device)
        print("✅ Stable Fast 3D model loaded and ready!")

    @modal.method()
    def generate(self, image_bytes: bytes) -> bytes:
        """
        Generate a 3D mesh from an image.

        Args:
            image_bytes: PNG image bytes (from SD-XL generation).

        Returns:
            .glb file as bytes.
        """
        import torch  # type: ignore
        import numpy as np  # type: ignore
        from PIL import Image as PILImage  # type: ignore
        import trimesh  # type: ignore
        import sys
        sys.path.insert(0, "/root/sf3d")
        from sf3d.utils import remove_background

        # Load image from bytes and convert to RGBA for background removal
        pil_image = PILImage.open(io.BytesIO(image_bytes)).convert("RGBA")
        
        # Remove background
        pil_image = remove_background(pil_image, self.rembg_session)

        # Resize if too large for faster processing
        w, h = pil_image.size
        if max(w, h) > MAX_IMAGE_SIZE:
            ratio = MAX_IMAGE_SIZE / max(w, h)
            new_size = (int(w * ratio), int(h * ratio))
            pil_image = pil_image.resize(new_size, PILImage.LANCZOS)
            print(f"📐 Resized image to {new_size} for faster 3D reconstruction")

        print("🎯 Running Stable Fast 3D reconstruction...")

        with torch.inference_mode():
            # Use autocast for faster inference if supported
            with torch.autocast(device_type="cuda", dtype=torch.bfloat16):
                mesh, materials = self.model.run_image(
                    pil_image,
                    bake_resolution=512,
                    remesh="triangle",     # triangle remeshing for clean topology
                    vertex_count=5000,     # mid-poly target (approx 10000 faces)
                )

        print(f"✅ Mesh generated: {len(mesh.vertices)} vertices, {len(mesh.faces)} faces")

        # Save mesh to .glb bytes
        glb_buf = io.BytesIO()
        mesh.export(glb_buf, file_type="glb", include_normals=True)
        glb_buf.seek(0)
        
        glb_size_kb = glb_buf.getbuffer().nbytes / 1024
        print(f"📦 GLB file size: {glb_size_kb:.1f} KB")
        
        return glb_buf.getvalue()


    @modal.method()
    def warm(self) -> str:
        """Lightweight method to keep the container alive without generating."""
        return "SF3D container is warm"

# --- Standalone test ---
@app.local_entrypoint()
def main():
    generator = SF3DGenerator()
    # Use a sample image from the web or a local path
    test_image_path = "test_sdxl_output.png"
    
    if not os.path.exists(test_image_path):
        print(f"⚠️ Test image not found at {test_image_path}")
        print("Run modal_sd_xl.py first to generate a test image, or provide your own.")
        return
    
    with open(test_image_path, "rb") as f:
        image_bytes = f.read()
    
    print("🧪 Testing SF3D generation...")
    glb_bytes = generator.generate.remote(image_bytes)
    
    output_path = "test_sf3d_output.glb"
    with open(output_path, "wb") as f:
        f.write(glb_bytes)
    print(f"✅ GLB saved to {output_path} ({len(glb_bytes) / 1024:.1f} KB)")