"""
Modal.com serverless deployment for Microsoft TRELLIS.
Converts images generated by SD-XL into 3D .glb models.

Architecture:
  - Deploys on Modal's Nvidia A10G 24GB
  - Image-to-3D reconstruction via TRELLIS
  - Includes nvdiffrast built natively on CUDA 11.8 Ubuntu container
  - Input: PNG image bytes
  - Output: .glb model bytes
"""

import io
import os
import modal
from modal import App, Image as ModalImage

# --- Modal App Definition ---
app = modal.App("greenscape-trellis")

# --- Build a Modal Image ---
# We use CUDA 11.8 devel image because nvdiffrast and spconv-cu118 compile seamlessly here.
trellis_image = (
    ModalImage.from_registry(
        "nvidia/cuda:11.8.0-devel-ubuntu22.04",
        setup_dockerfile_commands=[
            # libgl1-mesa-glx and libglib2.0-0 are required by OpenCV/PyVista
            "RUN apt-get update && apt-get install -y python3 python3-pip git ninja-build libgl1-mesa-glx libglib2.0-0 python-is-python3",
        ]
    )
    # Upgrade build tools FIRST so subsequent pip installs can parse PEP 621 pyproject.toml
    .pip_install("setuptools>=64", "wheel", "ninja")
    .pip_install(
        "torch==2.4.0+cu118",
        "torchvision==0.19.0+cu118",
        "xformers==0.0.27.post2",
        "numpy<2",
        "Pillow==11.1.0",
        "trimesh==4.5.2",
        "scipy==1.15.0",
        "huggingface_hub==0.29.0",
        "spconv-cu118",            # Sparse convolution for TRELLIS
        "xatlas",                  # Texture parametrization
        "pyvista",                 # Mesh decimation
        "pymeshfix",               # Hole filling
        "igraph",                  # Mesh processing
        "opencv-python-headless",  # Image processing
        "rembg",                   # Background removal (required by TRELLIS pipeline)
        "onnxruntime",             # Required by rembg
        "open3d",                  # 3D processing
        "transformers",            # Model loading
        "plyfile",                 # PLY mesh I/O (Gaussian representation)
        "requests",                # HTTP downloads
        "imageio",
        "imageio-ffmpeg",
        "easydict",
        "tqdm",
        "moderngl",                # Required by utils3d
        extra_index_url="https://download.pytorch.org/whl/cu118"
    )
    .env({
        "HF_HUB_ENABLE_HF_TRANSFER": "0",
        "USE_CUDA": "1",
        "ATTN_BACKEND": "xformers",
        "SPCONV_ALGO": "native",
        "TORCH_CUDA_ARCH_LIST": "8.6",   # A10G = Ampere SM86; prevents auto-detect crash during GPU-less build
    })
    .run_commands([
        # nvdiffrast pyproject.toml requires setuptools>=64 to parse the 'nvdiffrast' package name correctly.
        # We must use --no-build-isolation to allow setup.py to find the CUDA compiler from the torch installation.
        "git clone https://github.com/NVlabs/nvdiffrast.git /tmp/nvdiffrast && pip install /tmp/nvdiffrast --no-build-isolation",
        # utils3d fork must also be installed without build isolation to bypass metadata parsing bugs
        "git clone https://github.com/EasternJournalist/utils3d.git /tmp/utils3d && pip install /tmp/utils3d --no-build-isolation",
        # kaolin is required by flexicubes submodule
        "pip install kaolin -f https://nvidia-kaolin.s3.us-east-2.amazonaws.com/torch-2.4.0_cu118.html",
        # Clone TRELLIS repo WITH submodules (flexicubes is a git submodule)
        "git clone --recurse-submodules https://github.com/Microsoft/TRELLIS.git /root/trellis",
    ])
)

# Load HF token directly from .env without importing core
env_path = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), ".env")

@app.cls(
    image=trellis_image,
    gpu="A10G",
    timeout=600,       # 3D reconstruction can take longer
    secrets=[modal.Secret.from_dotenv(env_path)]
)
class TrellisGenerator:
    pipeline: object = None

    @modal.enter()
    def load_model(self):
        """Load the TRELLIS model into GPU memory."""
        import sys
        import torch  # type: ignore
        
        print("🚀 Loading TRELLIS Image-to-3D model onto GPU...")
        
        sys.path.insert(0, "/root/trellis")
        from trellis.pipelines import TrellisImageTo3DPipeline  # type: ignore
        
        # HF_TOKEN is expected by huggingface_hub
        if "HF_API_TOKEN" in os.environ:
            os.environ["HF_TOKEN"] = os.environ["HF_API_TOKEN"]
            
        self.pipeline = TrellisImageTo3DPipeline.from_pretrained(
            "JeffreyXiang/TRELLIS-image-large"
        )
        self.pipeline.cuda()
        
        if hasattr(self.pipeline, "enable_model_cpu_offload"):
            self.pipeline.enable_model_cpu_offload()
            
        print("✅ TRELLIS model loaded and ready!")

    @modal.method()
    def generate(self, image_bytes: bytes) -> bytes:
        """
        Generate a 3D mesh from an image using TRELLIS.

        Args:
            image_bytes: PNG image bytes.

        Returns:
            .glb file as bytes.
        """
        import sys
        import torch  # type: ignore
        from PIL import Image as PILImage  # type: ignore
        
        sys.path.insert(0, "/root/trellis")
        from trellis.utils import postprocessing_utils  # type: ignore

        # Load image from bytes
        img = PILImage.open(io.BytesIO(image_bytes)).convert("RGB")
        
        print("🎯 Running TRELLIS 3D reconstruction...")

        with torch.inference_mode():
            outputs = self.pipeline.run(img, seed=42)

        print("📐 Post-processing geometry and baking textures...")
        glb = postprocessing_utils.to_glb(
            outputs['gaussian'][0],
            outputs['mesh'][0],
            simplify=0.95,          # Decimate mesh to save filesize and memory
            texture_size=1024       # Cap texture size
        )

        # Save mesh to .glb bytes
        glb_buf = io.BytesIO()
        glb.export(file_obj=glb_buf)
        glb_buf.seek(0)
        
        glb_bytes = glb_buf.read()
        glb_size_kb = len(glb_bytes) / 1024
        print(f"📦 GLB file size: {glb_size_kb:.1f} KB")
        
        return glb_bytes

    @modal.method()
    def warm(self) -> str:
        """Lightweight method to keep the container alive without generating."""
        return "TRELLIS container is warm"

# --- Standalone test ---
@app.local_entrypoint()
def main():
    generator = TrellisGenerator()
    test_image_path = "test_sdxl_output.png"
    
    if not os.path.exists(test_image_path):
        print(f"⚠️ Test image not found at {test_image_path}")
        print("Please provide a test image to run the standalone test.")
        return
    
    with open(test_image_path, "rb") as f:
        image_bytes = f.read()
    
    print("🧪 Testing TRELLIS generation on Modal...")
    glb_bytes = generator.generate.remote(image_bytes)
    
    output_path = "test_trellis_output.glb"
    with open(output_path, "wb") as f:
        f.write(glb_bytes)
    print(f"✅ GLB saved to {output_path} ({len(glb_bytes) / 1024:.1f} KB)")
