"""
Modal.com serverless deployment for Stable Fast 3D (SF3D).
Converts images generated by SD-XL into 3D .glb models.

Architecture:
  - Deploys on Modal's Nvidia A100 40GB
  - Image-to-3D reconstruction via Stable Fast 3D
  - Input: PNG image bytes (from SD-XL output)
  - Output: .glb model bytes
"""

import io
import os
import tempfile
import modal
from modal import App, Image as ModalImage

# --- Modal App Definition ---
app = modal.App("greenscape-sf3d")

# --- Build a Modal Image ---
sf3d_image = (
    ModalImage.from_registry(
        "nvidia/cuda:12.4.0-devel-ubuntu22.04",
        setup_dockerfile_commands=[
            "RUN apt-get update && apt-get install -y python3 python3-pip git ninja-build",
        ]
    )
    .pip_install(
        "torch==2.6.0",
        "torchvision==0.21.0",
        "numpy<2",
        "Pillow==11.1.0",
        "trimesh==4.5.2",
        "scipy==1.15.0",
        "huggingface_hub==0.29.0",
    )
    .run_commands([
        "pip install git+https://github.com/Stability-AI/stable-fast-3d.git",
        'python -c "import subprocess; subprocess.run([\'python\', \'-m\', \'pip\', \'install\', \'ninja\', \'--upgrade\'], capture_output=True)"',
    ])
    .env({"HF_HUB_ENABLE_HF_TRANSFER": "0"})
)

# Images larger than this will be resized to speed up 3D reconstruction
MAX_IMAGE_SIZE = 1024


@app.cls(
    image=sf3d_image,
    gpu="A100",
    timeout=600,       # 3D reconstruction can take longer
    container_idle_timeout=120,
    keep_warm=1,        # Keep 1 warm alongside SD-XL
)
class SF3DGenerator:
    def __init__(self):
        self.model = None
        self.device = None

    @modal.enter()
    def load_model(self):
        """Load the Stable Fast 3D model into GPU memory."""
        import torch
        
        print("🚀 Loading Stable Fast 3D model onto GPU...")
        self.device = torch.device("cuda")
        
        # Import sf3d inside the container
        from sf3d.system import SF3D
        from huggingface_hub import hf_hub_download
        
        model_path = hf_hub_download(
            repo_id="stabilityai/stable-fast-3d",
            filename="sf3d.ckpt",
        )
        
        self.model = SF3D.load_from_checkpoint(
            model_path,
            map_location=self.device,
            config=None,
        )
        self.model.eval()
        self.model.to(self.device)
        print("✅ Stable Fast 3D model loaded and ready!")

    @modal.method()
    def generate(self, image_bytes: bytes) -> bytes:
        """
        Generate a 3D mesh from an image.

        Args:
            image_bytes: PNG image bytes (from SD-XL generation).

        Returns:
            .glb file as bytes.
        """
        import torch
        import numpy as np
        from PIL import Image as PILImage
        import trimesh

        # Load image from bytes
        pil_image = PILImage.open(io.BytesIO(image_bytes)).convert("RGB")

        # Resize if too large for faster processing
        w, h = pil_image.size
        if max(w, h) > MAX_IMAGE_SIZE:
            ratio = MAX_IMAGE_SIZE / max(w, h)
            new_size = (int(w * ratio), int(h * ratio))
            pil_image = pil_image.resize(new_size, PILImage.LANCZOS)
            print(f"📐 Resized image to {new_size} for faster 3D reconstruction")

        # Convert to tensor
        image_tensor = torch.from_numpy(np.array(pil_image)).float().permute(2, 0, 1) / 255.0
        image_tensor = image_tensor.unsqueeze(0).to(self.device)

        print("🎯 Running Stable Fast 3D reconstruction...")

        with torch.inference_mode():
            mesh, materials = self.model.run_image(
                image_tensor,
                bake_resolution=512,
                remesh="triangle",     # triangle remeshing for clean topology
                face_count=10000,      # mid-poly target (good for web rendering)
            )

        print(f"✅ Mesh generated: {len(mesh.vertices)} vertices, {len(mesh.faces)} faces")

        # Save mesh to .glb bytes
        glb_buf = io.BytesIO()
        mesh.export(glb_buf, file_type="glb", include_normals=True)
        glb_buf.seek(0)
        
        glb_size_kb = glb_buf.getbuffer().nbytes / 1024
        print(f"📦 GLB file size: {glb_size_kb:.1f} KB")
        
        return glb_buf.getvalue()


# --- Keep warm schedule ---
@app.function(
    image=sf3d_image,
    schedule=modal.Period(minutes=10),
)
def keep_warm():
    """Keep the SF3D container warm."""
    generator = SF3DGenerator()
    generator.load_model.remote()
    print("⏰ Keep-warm ping sent to SF3D container")


# --- Standalone test ---
@app.local_entrypoint()
def main():
    generator = SF3DGenerator()
    # Use a sample image from the web or a local path
    test_image_path = "/tmp/test_sdxl_output.png"
    
    if not os.path.exists(test_image_path):
        print(f"⚠️ Test image not found at {test_image_path}")
        print("Run modal_sd_xl.py first to generate a test image, or provide your own.")
        return
    
    with open(test_image_path, "rb") as f:
        image_bytes = f.read()
    
    print("🧪 Testing SF3D generation...")
    glb_bytes = generator.generate.remote(image_bytes)
    
    output_path = "/tmp/test_sf3d_output.glb"
    with open(output_path, "wb") as f:
        f.write(glb_bytes)
    print(f"✅ GLB saved to {output_path} ({len(glb_bytes) / 1024:.1f} KB)")